version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password  # Set your MySQL root password
      MYSQL_DATABASE: mh_record
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mh-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mh-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mh-network

volumes:
  mysql_data:

networks:
  mh-network:
    driver: bridge
