# Generated by Django 5.1.4 on 2025-01-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0005_remove_emotion_user_remove_journal_user_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for the user.', related_name='custom_user_permissions', to='auth.permission'),
        ),
    ]
