# Generated by Django 5.1.4 on 2025-01-22 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0008_alter_journalentry_patient_alter_patient_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.register'),
        ),
        migrations.AlterField(
            model_name='emotionlog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_logs', to='Record.register'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.register'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Record.register'),
        ),
    ]
